variable "environment" {}
variable "prefix" {}
variable "instance_type" {}
variable "key_name" {}
variable "application" {}
variable "allowed_cidr_blocks" {}
variable "bucket_functions" {}
variable "app_ami_id" {}
variable "web_ami_id" {}
